#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os.path, os, sys, re
from gitdh import gitdh, git, gitdhutils
from tempfile import NamedTemporaryFile

if len(sys.argv) >= 2 and sys.argv[1] == "--install":
	source = gitdhutils.getExePath(os.path.basename(__file__))
	symlink = "post-receive"
	if len(sys.argv) >= 4 and sys.argv[2] == "--name":
		symlink = sys.argv[3]
	os.symlink(source, symlink)
	exit(0)

hooksPath = os.path.dirname(os.path.abspath(__file__))
repositoryDir = os.path.abspath(os.path.join(hooksPath, os.pardir))
repositoriesDir = os.path.abspath(os.path.join(repositoryDir, os.pardir))
repositoryName = os.path.basename(repositoryDir)
if repositoryName.rfind(".git") == len(repositoryName) - 4:
	repositoryName = repositoryName[:len(repositoryName) - 4]
gC = git.Git(repositoryDir=repositoryDir)

if not "gitdh" in gC.getBranches():
	exit(0)


gFile = None
for file in gC.getFiles(branch="gitdh"):
	if file.getFileName() == "gitdh.conf":
		gFile = file
		break
if gFile == None:
	exit(0)

tmpConfigFile = NamedTemporaryFile()
tmpConfigFile.write(gFile.getFileContent().encode())
tmpConfigFile.flush()

try:
	while True:
		rawInput = input()
		gitdh.gitDhMain(tmpConfigFile.name, "postreceive", rawInput.split(" "), repositoryName=repositoryName, repositoriesDir=repositoriesDir)
except EOFError:
	pass
except Exception:
	raise

tmpConfigFile.close()
