#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from gitdh.gitdh import gitDhMain
import sys, os.path

def printHelp(exitValue=0):
	print(
"""	Git Deployment Handler v0.6
Usage:
        git-dh [--help] <configfile> <action> [args...]
Parameters:
        configfile - path to the config file
        action     - context of the script, see below
        args       - additional arguments dependent on the action
Options:
        -h         - shortcut for --help
        --help     - print this message and exit
Actions:
    postreceive    - 
        
    cron           - 
        """)
	exit(exitValue)

def cliMain():
	if len(sys.argv) >= 2 and (sys.argv[1] == "-h" or sys.argv[1] == "--help"):
		printHelp(1)

	if len(sys.argv) < 3:
		print("Missing parameters, try {0} --help".format(sys.argv[0]))
		exit(1)

	configFile = sys.argv[1]
	action = sys.argv[2]
	args = sys.argv[3:]

	if not os.path.isfile(configFile):
		syslog(LOG_INFO, "Couldn't find config file '{0}'".format(configFile))
		exit(1)

	gitDhMain(configFile, action, args)

if __name__ == "__main__":
	cliMain()
