#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os.path, os, sys, re
from gitdh import gitdh, git, gitdhutils
from tempfile import NamedTemporaryFile

for arg in sys.argv[1:]:
	repositoryDir = os.path.abspath(arg)
	repositoriesDir = os.path.abspath(os.path.join(repositoryDir, os.pardir))
	repositoryName = os.path.basename(repositoryDir)
	if repositoryName.rfind(".git") == len(repositoryName) - 4:
		repositoryName = repositoryName[:len(repositoryName) - 4]
	gC = git.Git(repositoryDir=repositoryDir)

	if not "gitdh" in gC.getBranches():
		continue

	gFile = None
	for file in gC.getFiles(branch="gitdh"):
		if file.getFileName() == "gitdh.conf":
			gFile = file
			break
	if gFile == None:
		continue

	tmpConfigFile = NamedTemporaryFile()
	tmpConfigFile.write(gFile.getFileContent().encode())
	tmpConfigFile.flush()

	gitdh.gitDhMain(tmpConfigFile.name, "cron", (), repositoryName=repositoryName, repositoriesDir=repositoriesDir)

	tmpConfigFile.close()
